### PR TITLE
Improvement

### PR DESCRIPTION
**Pull request by Namithajacob**
We have created a cpp file : limit_output.cpp, which has a void function which takes input file, output file and ellipsis as input and the output file of the simulator will print only the inputs we took from the ellipsis. Here, we used a structure which has two members and after comparing port and component of the input file with structure members, the void function will write to a new file limit_output.txt.

Kindly review our code and give your feedback

### CODE REVIEW

**Comment by mitalraithatha** [comment]
Your output file's column names("headings- "PORT","VALUE") are not showing in synchronization.
In limit_output.cpp file -in line 63 you need to adjust the tab size according to your requirements.
that will work and you will get outputs in sync.

**Comment by Namithajacob** [comment]
Changed the Alignment of the output files based on the reviews.

**Review by mitalraithatha — APPROVED** [review]
yes now it is coming properly in output files.
Approved

**Review by SREEJITH1991 — COMMENTED** [review]
convert all '\t' character to spaces as in most of our local editors tab=4spaces, but in git hub 1tab=8spaces,
thereby causing indentation issue.
Please check in all files you have edited as part of indentation task

**Comment by mitalraithatha** [comment]
Hello,
In README.md file 	instead of "./SUBNET_TEST" it should ne **"./SUBNET "** as your executable file name is ./SUBNET.
In next line by mistake you put one   [ \ ] after test and before output. so need to remove that.	  
    **To check the output of the test, open  "../test/data/subnet_test\_output.txt"**

**Comment by mitalraithatha** [comment]
In your SUBNET -> output.txt file is not coming with all data.Only title is coming but no data are coming.
Check that and make necessary changes.

**Comment by mitalraithatha** [comment]
In your RECEIVER ->In  limit_output file has also data missing.
Title it is coming "TIME", "VALUE" , "COMPONENT","PORT" but inside that title data is not coming.
Please look into that.

**Review by mitalraithatha — CHANGES_REQUESTED** [review]
New changes requested in comments.

**Comment by dilsgeorge** [comment]
> Hello,
> In README.md file instead of "./SUBNET_TEST" it should ne **"./SUBNET "** as your executable file name is ./SUBNET.
> In next line by mistake you put one [ \ ] after test and before output. so need to remove that.
> **To check the output of the test, open "../test/data/subnet_test_output.txt"**

changes are made

**Comment by dilsgeorge** [comment]
> In your SUBNET -> output.txt file is not coming with all data.Only title is coming but no data are coming.
> Check that and make necessary changes.

changes are made

**Comment by dilsgeorge** [comment]
> In your RECEIVER ->In limit_output file has also data missing.
> Title it is coming "TIME", "VALUE" , "COMPONENT","PORT" but inside that title data is not coming.
> Please look into that.

it because in parte in new output file only the matching data with structure members will come.
made changes to show if there is any out put in new file

**Review by SREEJITH1991 — APPROVED** [review]
approved

**Review by mitalraithatha — APPROVED** [review]
All Changes done according to review.
Thanks.
So approving it.

**Pull request merged**
